name: Build CED

on:
  push:
    branches: [ "main", "port-cinput-ced-to-cpp" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/therainbowphoenix/gint-docker:main

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Build (fxsdk build-cp)
      run: |
        fxsdk build-cp

    - name: Upload CED.hh3
      uses: actions/upload-artifact@v4
      with:
        name: CED.hh3
        path: build-cp/CED.hh3
